export const ALL_AUCTIONS = "ALL_AUCTIONS";
export const ALL_AUCTIONS_SUCCESS = "ALL_AUCTIONS_SUCCESS";
export const ALL_AUCTIONS_FAILURE = "ALL_AUCTIONS_FAILURE";

export const AUCTION_BY_ID = "AUCTION_BY_ID";
export const AUCTION_BY_ID_SUCCESS = "AUCTION_BY_ID_SUCCESS";

export const ADD_AUCTION = "ADD_AUCTION";
export const ADD_AUCTION_SUCCESS = "ADD_AUCTION_SUCCESS";
export const ADD_AUCTION_FAILURE = "ADD_AUCTION_FAILURE";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_TEMP_PRICE = "UPDATE_PRODUCT_TEMP_PRICE";
export const UPDATE_PRODUCT_PRICE_WITH_ID = "UPDATE_PRODUCT_PRICE_WITH_ID";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const BID_PRICE = "BID_PRICE";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const GET_CATEGORIES = "GET_CATEGORIES";

export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const GET_PERSONAL_FAVORITES_CATEGORIES =
  "GET_PERSONAL_FAVORITES_CATEGORIES";

export const ALL_NOTIFICATIONS = "ALL_NOTIFICATIONS";
export const MARK_ALL_AS_READ = "MARK_ALL_AS_READ";
