export const ALL_AUCTIONS = "ALL_AUCTIONS";
export const ALL_AUCTIONS_SUCCESS = "ALL_AUCTIONS_SUCCESS";
export const ALL_AUCTIONS_FAILURE = "ALL_AUCTIONS_FAILURE";

export const AUCTION_BY_ID = "AUCTION_BY_ID";
export const AUCTION_BY_ID_SUCCESS = "AUCTION_BY_ID_SUCCESS";

export const ADD_AUCTION = "ADD_AUCTION";
export const ADD_AUCTION_SUCCESS = "ADD_AUCTION_SUCCESS";
export const ADD_AUCTION_FAILURE = "ADD_AUCTION_FAILURE";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
export const REMOVE_PRODUCT_FAILURE = "REMOVE_PRODUCT_FAILURE";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const ALL_MANUFACTURERS = "ALL_MANUFACTURER";
export const ALL_MANUFACTURERS_SUCCESS = "ALL_MANUFACTURER_SUCCESS";

export const ERROR_MSG = "ERROR_MSG";
export const SUCCESS_MSG = "SUCCESS_MSG";
